### ISSUE TITLE
Documentation request - aggregation queries

### ISSUE THREAD

**Issue by iainmwallace** [solvebio/solvebio-r#59]
Hi,

Can you provide some documentation on how to perform simple aggregations with solve bio? 
For example, it would be great to replicate examples for the dplyr package with the flights dataset
http://manishbarnwal.com/blog/2017/05/15/tutorial_on_dplyr/

Thanks

Iain

**Comment by davecap** [comment]
Here is a gist that does a few aggregations in Python: https://gist.github.com/davecap/2e81275c355566da15778af4ff106809

I will port this over to R and add it to this repo as well.

**Comment by davecap** [comment]
Here are some examples of how you could use aggregations (facets) on the flights dataset: https://github.com/solvebio/solvebio-r/blob/master/examples/aggregation_queries_flights.Rmd

It isn't ideal because you currently cannot run nested aggregations in a single API call. It may be possible to add in the future.

**Comment by davecap** [comment]
Here's an example in our docs page about nested aggregations: https://docs.solvebio.com/datasets/aggregating/#nested-aggregations

**Comment by davecap** [comment]
Nested aggregations example available (nyc flights dataset) here: https://github.com/solvebio/solvebio-r/blob/master/examples/flights.R
